import os
import shutil

from celery.result import AsyncResult
from fastapi import FastAPI, File, HTTPException, UploadFile

from tasks import celery_app, process_drone_mission

app = FastAPI(title="Drone Photogrammetry Pipeline API")

UPLOAD_DIR = "./storage/raw_missions"
OUTPUT_DIR = "./storage/completed_maps"


@app.post("/api/v1/maps/process")
async def upload_and_stitch_map(file: UploadFile = File(...)):
    if not file.filename.endswith(".zip"):
        raise HTTPException(
            status_code=400, detail="Only compressed .zip folders are supported."
        )

    os.makedirs(UPLOAD_DIR, exist_ok=True)

    file_location = os.path.join(UPLOAD_DIR, file.filename)
    with open(file_location, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    mission_id = os.path.splitext(file.filename)[0]
    result_path = os.path.abspath(os.path.join(OUTPUT_DIR, mission_id))

    # Capture the unique background task ID generated by Celery
    async_task = process_drone_mission.delay(
        os.path.abspath(file_location), result_path
    )

    return {
        "message": "Drone mission dataset successfully queued for processing.",
        "mission_id": mission_id,
        "task_id": async_task.id,  # Returning the task ID so the frontend can track it
        "status": "Processing asynchronously in background",
    }


@app.get("/api/v1/maps/status/{task_id}")
async def get_processing_status(task_id: str):
    """
    Pings Celery and the local storage to check the health/status of a mapping run.
    """
    task_result = AsyncResult(task_id, app=celery_app)

    # Check Celery states (PENDING, STARTED, SUCCESS, FAILURE)
    state = task_result.state

    response = {"task_id": task_id, "pipeline_state": state, "output": None}

    if state == "SUCCESS":
        # If Celery finished, grab the payload returned by tasks.py
        response["output"] = task_result.result
    elif state == "FAILURE":
        # If it crashed globally, return the error message string
        response["output"] = {"status": "FAILED", "error": str(task_result.info)}

    return response
